version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace
    ports:
      - '8000:8000'
      - '5173:5173'
    environment:
      - PYTHONPATH=/workspace
      - NODE_ENV=development
    command: sleep infinity
