name: CI

on:
  push:
  pull_request:

jobs:
  backend:
    name: Backend (Python)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirement.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Static syntax check
        run: |
          python - << 'PY'
          import subprocess, sys
          import os
          files = subprocess.check_output(['git', 'ls-files', '*.py']).decode().splitlines()
          if not files:
              sys.exit(0)
          for f in files:
              subprocess.check_call([sys.executable, '-m', 'py_compile', f])
          PY

  frontend:
    name: Frontend (Node)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Build
        run: npm run build


