name: Test PC Express (Local Development)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Test backend imports
        run: |
          python -c "import app.main; print('Backend imports successfully')"
          python -c "from app.database import engine; print('Database connection successful')"

      - name: Test backend syntax
        run: |
          python -m py_compile app/main.py
          python -m py_compile app/database.py
          python -m py_compile app/models.py
          echo "Backend syntax check passed"

  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Test frontend build
        run: |
          cd frontend
          npm run build

      - name: Check for critical vulnerabilities
        run: |
          cd frontend
          npm audit --audit-level high
